"""
Constants and enumerations for Darknet framework
"""

# 802.11 Frame Types
FRAME_TYPE_MANAGEMENT = 0x00
FRAME_TYPE_CONTROL = 0x01
FRAME_TYPE_DATA = 0x02

# 802.11 Management Subtypes
SUBTYPE_ASSOC_REQ = 0x00
SUBTYPE_ASSOC_RESP = 0x01
SUBTYPE_REASSOC_REQ = 0x02
SUBTYPE_REASSOC_RESP = 0x03
SUBTYPE_PROBE_REQ = 0x04
SUBTYPE_PROBE_RESP = 0x05
SUBTYPE_BEACON = 0x08
SUBTYPE_DISASSOC = 0x0a
SUBTYPE_AUTH = 0x0b
SUBTYPE_DEAUTH = 0x0c

# Deauth Reason Codes
REASON_UNSPECIFIED = 1
REASON_PREV_AUTH_NOT_VALID = 2
REASON_DEAUTH_LEAVING = 3
REASON_DISASSOC_DUE_TO_INACTIVITY = 4
REASON_CLASS2_FRAME_FROM_NONAUTH_STA = 6
REASON_CLASS3_FRAME_FROM_NONASSOC_STA = 7
REASON_DISASSOC_STA_HAS_LEFT = 8
REASON_MIC_FAILURE = 14
REASON_4WAY_HANDSHAKE_TIMEOUT = 15
REASON_CIPHER_SUITE_REJECTED = 24

# WiFi Channels
WIFI_CHANNELS_2GHZ = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
WIFI_CHANNELS_5GHZ = [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165]
WIFI_CHANNELS_6GHZ = list(range(1, 233, 4))  # WiFi 6E channels

# Encryption Types
ENCRYPTION_OPEN = "OPEN"
ENCRYPTION_WEP = "WEP"
ENCRYPTION_WPA = "WPA"
ENCRYPTION_WPA2 = "WPA2"
ENCRYPTION_WPA3 = "WPA3"
ENCRYPTION_WPA_WPA2 = "WPA/WPA2"
ENCRYPTION_WPA2_WPA3 = "WPA2/WPA3"

# Authentication Types
AUTH_OPEN = "OPEN"
AUTH_PSK = "PSK"
AUTH_SAE = "SAE"  # WPA3
AUTH_EAP = "EAP"
AUTH_OWE = "OWE"  # Enhanced Open

# Attack Types
ATTACK_DEAUTH = "deauth"
ATTACK_DISASSOC = "disassoc"
ATTACK_EVIL_TWIN = "evil_twin"
ATTACK_ROGUE_AP = "rogue_ap"
ATTACK_PMKID = "pmkid"
ATTACK_HANDSHAKE = "handshake"
ATTACK_KRACK = "krack"
ATTACK_DRAGONBLOOD = "dragonblood"
ATTACK_BEACON_FLOOD = "beacon_flood"
ATTACK_AUTH_FLOOD = "auth_flood"
ATTACK_FRAGMENTATION = "fragmentation"
ATTACK_CAFFE_LATTE = "caffe_latte"
ATTACK_HIRTE = "hirte"

# Detection Types
DETECT_DEAUTH_ATTACK = "deauth_attack"
DETECT_ROGUE_AP = "rogue_ap"
DETECT_EVIL_TWIN = "evil_twin"
DETECT_BEACON_FLOOD = "beacon_flood"
DETECT_PROBE_REQUEST_FLOOD = "probe_request_flood"
DETECT_HANDSHAKE_CAPTURE = "handshake_capture"
DETECT_JAMMING = "jamming"
DETECT_UNUSUAL_TRAFFIC = "unusual_traffic"

# Color codes for terminal output
COLOR_RED = '\033[91m'
COLOR_GREEN = '\033[92m'
COLOR_YELLOW = '\033[93m'
COLOR_BLUE = '\033[94m'
COLOR_MAGENTA = '\033[95m'
COLOR_CYAN = '\033[96m'
COLOR_WHITE = '\033[97m'
COLOR_RESET = '\033[0m'
COLOR_BOLD = '\033[1m'

# Attack severity levels
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

# Default timeouts (seconds)
TIMEOUT_SCAN = 30
TIMEOUT_HANDSHAKE = 120
TIMEOUT_PMKID = 60
TIMEOUT_DEAUTH = 10

# Packet injection rates (packets per second)
INJECTION_RATE_SLOW = 10
INJECTION_RATE_NORMAL = 50
INJECTION_RATE_FAST = 100
INJECTION_RATE_AGGRESSIVE = 200

# EAPOL Key Information flags
EAPOL_KEY_INFO_PAIRWISE = 0x0008
EAPOL_KEY_INFO_INSTALL = 0x0040
EAPOL_KEY_INFO_ACK = 0x0080
EAPOL_KEY_INFO_MIC = 0x0100
EAPOL_KEY_INFO_SECURE = 0x0200
EAPOL_KEY_INFO_ERROR = 0x0400
EAPOL_KEY_INFO_REQUEST = 0x0800
EAPOL_KEY_INFO_ENCRYPTED = 0x1000

# WPA/WPA2/WPA3 Constants
WPA_NONCE_SIZE = 32
WPA_MIC_SIZE = 16
WPA_PTK_SIZE = 64
WPA_PMK_SIZE = 32

# Interface modes
MODE_MANAGED = "managed"
MODE_MONITOR = "monitor"
MODE_MASTER = "master"
MODE_AD_HOC = "ad-hoc"

# Vendor OUIs (Organizationally Unique Identifiers)
VENDOR_OUIS = {
    "00:03:7F": "Atheros",
    "00:0C:43": "Ralink",
    "00:13:10": "Linksys",
    "00:14:BF": "Netgear",
    "00:1B:63": "D-Link",
    "00:24:01": "Broadcom",
    "00:50:F2": "Microsoft",
    "00:90:4C": "Epigram (Broadcom)",
    "E0:91:F5": "TP-Link",
    "F8:1A:67": "TP-Link",
}

# RSN Capabilities
RSN_CAPABILITY_PREAUTH = 0x0001
RSN_CAPABILITY_PAIRWISE = 0x0002
RSN_CAPABILITY_MGMT_FRAME_PROTECTION_REQUIRED = 0x0040
RSN_CAPABILITY_MGMT_FRAME_PROTECTION_CAPABLE = 0x0080

# Module status
STATUS_IDLE = "idle"
STATUS_RUNNING = "running"
STATUS_PAUSED = "paused"
STATUS_STOPPED = "stopped"
STATUS_ERROR = "error"

# Log levels
LOG_DEBUG = "DEBUG"
LOG_INFO = "INFO"
LOG_WARNING = "WARNING"
LOG_ERROR = "ERROR"
LOG_CRITICAL = "CRITICAL"
